### ISSUE TITLE
Can I build this on my web?

### ISSUE THREAD

**Issue by carry0987** [kennedyoliveira/github-basic-badges#1]
I want to know how to build this on my website..
Thanks!

**Comment by kennedyoliveira** [comment]
hey @carry0987 ! Could you elaborate a little about what exactly you want to do? You need like a separate service for this, or you want to embed this?
There is a explanation on the Readme on how to deploy it easily on heroku.

**Comment by carry0987** [comment]
Hello,very thanks you for this reply,I mean can I build this service to my web? 
For Example: [www.nehscsa.com](www.nehscsa.com) is my website url,can I build this github release badge on my web? The link will be like
`www.nehscsa.com/release/<user>/<repo>.svg`

**Comment by carry0987** [comment]
I want to do this because in my country,someone is hard to connect to 
`herokuapp.com`

I will write down your name if I success build it on my web.
Thanks you very much!!!

P.s. Sorry for my bad english,I am still learning it.

**Comment by kennedyoliveira** [comment]
hey @carry0987 , i see now, if your site is written in ruby you can, since this project is in ruby. It's using sinatra, if you are using it too, that will make a piece of cake to implement, otherwise will require some modification.

**Comment by carry0987** [comment]
Thanks for your reply,but my wed site is written in js,php,html,xml....
If it can be convert to js or php,I can use this....QAQ

Thanks you very much!! This badge project is the best!

**Comment by kennedyoliveira** [comment]
Ah i see, well i can help you with how it works, but i have no knowledge of php, so i can't help with writing it in that language.

**Comment by kennedyoliveira** [comment]
Just out of curiosity, what is QAQ? It's a emoticon? haha

**Comment by carry0987** [comment]
I will learn ruby and try to build it in php or js,after my university test,I will make it,if I have any questions about this,can I ask you?

P.s. QAQ is the text-emoji ,it means sad

**Comment by kennedyoliveira** [comment]
Ahh i didn't know this emoticon haha.

> if I have any questions about this,can I ask you?

Sure, no problem, i'll be glad to help.

**Comment by carry0987** [comment]
Thanks you very much!!

**Comment by kennedyoliveira** [comment]
Your welcome! :)

**Comment by carry0987** [comment]
Hello,I want to know which version of ruby did you use to make this project?
And,I saw `https://img.shields.io` this url in your `badge_utils.rb` file, can it change to other site?
Example: https://www.nehscsa.com/static/status/release.svg

**Comment by kennedyoliveira** [comment]
Hey, i used version `2.2.3`, about the url you can change, i use this site to generate the badges for me, the SVG, if your other site generates you can use without problem, just check if it supports all the semantics, like colors, etc

**Comment by carry0987** [comment]
Thanks!!
